name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          git config --global user.email "iasmin@webonesystem.com.br"
          git config --global user.name "iasminWebOne"
          git clone https://huggingface.co/spaces/HosanaIasmin08/classificacao-topico-de-texto-noah
          rsync -av --exclude='classificacao-topico-de-texto-noah' . classificacao-topico-de-texto-noah/
          cd classificacao-topico-de-texto-noah
          git remote set-url origin https://$GH_PAT@github.com/HosanaIasmin/Classificacao-topicos-de-texto.git
          git add .
          git commit -m "Update space with new model"
          git push
